apiVersion: v1
metadata:
  labels:
    some-label: slave-lable
kind: Pod
spec:
  containers:
  - name: docker
    image: docker:latest
    command:
    - cat
    tty: true
  - name: ubuntu
    image: ubuntu:latest
    command:
    - cat
    tty: true
