apiVersion: v1
kind: Pod
spec:
  containers:
  - name: docker
    image: docker
    command:
    - sleep
    args:
    - infinity
  - name: ubuntu
    image: ubuntu
    command:
    - sleep
    args:
    - infinity
